# Generated by Django 5.2.1 on 2025-05-28 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Обрабатывается'), ('done', 'Завершено'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('views_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимум просмотров')),
                ('likes_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимум лайков')),
                ('comments_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимум комментариев')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Дата от')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата до')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Ключевые слова или хэштеги')),
                ('limit', models.PositiveIntegerField(default=50, verbose_name='Лимит на количество результатов')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='exports/', verbose_name='Готовый CSV-файл')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
            ],
            options={
                'verbose_name': 'Поиск reel',
                'verbose_name_plural': 'Поиск reels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=2048, verbose_name='Ссылка на видео')),
                ('author_username', models.CharField(max_length=500, verbose_name='Никнейм автора')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('description', models.TextField(blank=True, verbose_name='Описание поста')),
                ('hashtags', models.TextField(blank=True, verbose_name='Хэштеги')),
                ('views', models.PositiveIntegerField(verbose_name='Количество просмотров')),
                ('likes', models.PositiveIntegerField(verbose_name='Количество лайков')),
                ('comments', models.PositiveIntegerField(verbose_name='Количество комментариев')),
                ('sound_url', models.URLField(blank=True, max_length=2048, null=True, verbose_name='Ссылка на звук')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.searchtask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Найденный Reels',
                'verbose_name_plural': 'Найденные Reels',
            },
        ),
        migrations.CreateModel(
            name='SearchRawResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('author_username', models.CharField(blank=True, max_length=500, null=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('sound_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_results', to='core.searchtask')),
            ],
            options={
                'verbose_name': 'Сырой рилс',
                'verbose_name_plural': 'Сырые рилсы',
                'ordering': ['-created_at'],
            },
        ),
    ]
