# Generated by Django 5.2.1 on 2025-05-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtask',
            name='limit',
            field=models.PositiveIntegerField(default=50, verbose_name='Лимит на количество результатов'),
        ),
    ]
